services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file:
      - .env.prod
    restart: unless-stopped
    networks:
      - backend
      - public

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    env_file:
      - .env.prod
    ports:
      - "30002:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - public

networks:
  backend:
    driver: bridge
  public:
    driver: bridge