edition = "2024"
newline_style = "Unix"

max_width = 100
hard_tabs = false
tab_spaces = 4

use_small_heuristics = "Max"

fn_call_width = 60
chain_width = 60
single_line_if_else_max_width = 50

reorder_imports = true